version: "3"
services:
  payment_API:
    image: thenatz1999/ecamazon_payment_api
    ports:
      - "3000:3000"
    command: "nodemon server.js"
    volumes:
      - ./payment-api/:/app
    environment:
      CASSANDRA_HOST: payment_DB
      CASSANDRA_KEYSPACE: ecamazon_payment
    networks:
      payment_network:
        ipv4_address: 192.168.92.21
    restart: on-failure

    depends_on:
      - payment_DB

  payment_DB:
    image: cassandra
    ports:
      - "9042:9042"

    networks:
      payment_network:
        ipv4_address: 192.168.92.20
    volumes:
      - ./my_cassandra_storage:/var/lib/cassandra

  payment_frontend:
    image: thenatz1999/ecamazon_payment_front
    ports:
      - "4000:4000"
    command: "npm run dev"
    # volumes:
    #   - ./payment-frontend/:/app/
    environment:
      REACT_APP_API_CONTACT_POINT: 192.168.92.21 # should match API container ip
    networks:
      payment_network:
        ipv4_address: 192.168.92.22

networks:
  payment_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
