# node-api-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecamazon-payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecamazon-payment-api
  template:
    metadata:
      labels:
        app: ecamazon-payment-api
    spec:
      containers:
        - name: ecamazon-payment-api
          # image: thenatz1999/ecamazon_payment_api_linux # ecam linux cluster
          # IN TEST
          image: thenatz1999/ecamazon_payment_api_minikube #my computer with multiple db replicas
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CASSANDRA_HOST
              value: ecamazon-payment-db
            - name: CASSANDRA_KEYSPACE
              value: ecamazon_payment
              # ONLY WHEN USING THE IMAGE : ecamazon_payment_api_mutliple_db
            - name: CASSANDRA_REPLICAS
              value: "1"
            # - name: API_PORT
            #   value: "3070"
---
apiVersion: v1
kind: Service
metadata:
  name: ecamazon-payment-api
spec:
  type: LoadBalancer
  ports:
    - port: 3040
      targetPort: 3000
      # REMOVE FOR LOCAL : minikube
      nodePort: 30009 # ecamazon1
      # nodePort: 30021 # ecamazon2

  selector:
    app: ecamazon-payment-api
