name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to the project root
        run: cd $GITHUB_WORKSPACE

      - name: Debugging
        run: |
          pwd
          ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Change to the desired directory
        run: cd payment-api

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
