name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debugging
        run: |
          pwd
          ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Change to the project root
        run: cd $GITHUB_WORKSPACE

      - name: This should be root path
        run: cd $GITHUB_WORKSPACE

      - name: Change to the desired directory
        run: cd ecamazon_payment_microservice/payment-api

      - name: Current directory
        run: pwd

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
